routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});
Route::resource('/claim', 'ClaimController',
['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']]
);

Route::resource('/comment', 'CommentController',
['only' => ['store']]
);

app/Claim.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
class Claim extends Model
{
  protected $fillable = [
          'description',
          'status',
      ];
  public function comments(){
    return $this->HasMany('App\Comment');
  }

  static function status($statusid){
    $status[1] = 'Новая';
    $status[2] = 'В работе';
    $status[3] = 'Решена';
    $status[4] = 'Отклонена';
    return $status[$statusid];
  }
}

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
  protected $fillable = [
          'claim_id',
          'description',
      ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ClaimController.php
<?php

namespace App\Http\Controllers;

use App\Claim;
use Illuminate\Http\Request;

class ClaimController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $claims = Claim::with('comments')->get();
        return view('index', compact('claims'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $description = $request->description;
        $status = 1;
        Claim::create(['description' => $description, 'status' => $status]);
        return redirect()->route('claim.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Claim  $claim
     * @return \Illuminate\Http\Response
     */
    public function show(Claim $claim)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Claim  $claim
     * @return \Illuminate\Http\Response
     */
    public function edit(Claim $claim)
    {
      $claim = Claim::findOrFail($claim)[0];

      return view('edit', compact('claim'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Claim  $claim
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Claim $claim)
    {
      $claim_id = $claim->id;
      $description = $request->description;
      $status = $request->status;
      Claim::where('id', $claim_id)
      ->update(['description' => $description, 'status' => $status]);
      return redirect()->route('claim.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Claim  $claim
     * @return \Illuminate\Http\Response
     */
    public function destroy(Claim $claim)
    {
      Claim::findOrFail($claim);
      $claim->delete();
      return redirect()->back();
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $claim_id = $request->claim_id;
        $description = $request->description;
        Comment::create(['claim_id' => $claim_id, 'description' => $description]);
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function show(Comment $comment)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function edit(Comment $comment)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Comment $comment)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $comment)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/create.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
    </head>
    <body>

            <div class="content">
              <form action="{{route('claim.store')}}" method="post">
                {{csrf_field()}}
                <input type="text" name="description" placeholder="Описаие">
                <button type="submit" name="button">Создать</button>
              </form>
            </div>

    </body>
</html>

resources/views/edit.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
    </head>
    <body>

            <div class="content">
              <form action="{{route('claim.update', $claim->id)}}" method="post">
                {{csrf_field()}}
                <input type="hidden" name="_method" value="put">
                <input type="text" name="description" value="{{$claim->description}}" placeholder="Описаие">
                <select  name="status">
                  <option value="1" @if($claim->status == 1) selected @endif>Новая</option>
                  <option value="2" @if($claim->status == 2) selected @endif>В работе</option>
                  <option value="3" @if($claim->status == 3) selected @endif>Решена</option>
                  <option value="4" @if($claim->status == 4) selected @endif>Отклонена</option>
                </select>
                <button type="submit" name="button">Создать</button>
              </form>
            </div>

    </body>
</html>

resources/views/index.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
    </head>
    <body>

            <div class="content">
              <a href="{{route('claim.create')}}">Создать заявку</a>
              <table>
                <thead>
                  <tr>
                    <th>№ Заявки</th>
                    <th>Описание</th>
                    <th>Статус</th>
                    <th>Комментарии</th>
                  </tr>
                </thead>
                <tbody>
                  @forelse($claims as $claim)
                  <tr>
                    <td>{{$claim->id}}</td>
                    <td>{!! $claim->description !!}</td>
                    <td>{{Claim::status($claim->status)}}</td>
                    <td><a href="{{route('claim.edit', $claim->id)}}">Редактировать</a> </td>
                    <td>
                      <form  action="{{route('claim.destroy', [$claim->id])}}" method="post">
                        {{csrf_field()}}
                        <input type="hidden" name="_method" value="DELETE">
                        <button type="submit" name="button">Удалить</button>
                      </form>
                     </td>
                    <td>

                      @forelse($claim->comments as $comment)
                      <li>id: {{$comment->id}}</li>
                      <li>Оп: {!! $comment->description !!}</li>
                      @empty
                      @endforelse
                      <form action="{{route('comment.store')}}" method="post">
                        {{csrf_field()}}
                        <input type="hidden" name="claim_id" value="{{$claim->id}}">
                        <input type="text" name="description" placeholder="Описание">
                        <button type="submit" name="button">Отправить</button>
                      </form>
                    </td>
                  </tr>
                  @empty
                  @endforelse
                </tbody>
              </table>
            </div>

    </body>
</html>